### PR TITLE
Shock/retrieve

### PR DESCRIPTION
**Pull request by shock**
@therealadam - I would like to merge this in.  It's super helpful for debugging.  I wrote a backing test and have tested it in the rails console on the app side.  I'm confident it won't have any side-effects, harmful or otherwise.

### CODE REVIEW

**Comment by therealadam** [comment]
This will work in a console that can talk to Cassandra, but not from a client. You'll need to add a handler in App to get that. Start with a test in API tests and pull a string through it from there.

**Comment by shock** [comment]
Actually, it does work from the client.  Because the `get "/object/:object_key" do` method is already defined in app.rb: https://github.com/gowalla/chronologic/blob/master/lib/chronologic/service/app.rb#L15

The only thing needed was to add the method to the client.  I have verified from the client's perspective.  I even started to write a functional test, but ran into problems with my test environment, and aborted.

**Comment by shock** [comment]
Please merge if you are ok with this.  Thanks.

**Comment by shock** [comment]
Going ahead with the merge.  We can revert if you have any concerns.

**Pull request merged**
